name: contributor-push-spec-action
on: [pull_request]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Project
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.lock.json') }}
      - run: npm i
      - run: NEW_USER=$(git show main:contributors.json | jq -r --argjson new "$(cat contributors.json)" '. | keys - ($new | keys) | join(",")') npm run test

      - if: ${{ failure() }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            It looks like you haven't order the JSON values in ascending order alphabetically ignoring case by Github user name or your JSON syntax is wrong. Please read the issue description before taking them.
            If you know about nodejs run the following command to sort the list:
            ```sh
              npx sort-json contributors.json --ignore-case
            ```
            **If you don't know about node js, go the following link:**
            https://codeshack.io/json-sorter/
            Paste the content of the file and generate a sorted JSON. After the paste the sorted list in the file and make a commit.

            Once this is done, your PR will be reviewed and merged.

            If you still have problem you can tag in a maintainer: @subeshb1
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false
